apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: monitoring
  labels:
    name: grafana-configmap
data:
  grafana.ini: |
    # [auth]
    # disable_login_form = true
    # disable_signout_menu = true
    # [auth.anonymous]
    # enabled = true
    # org_name = Main Org.
    # org_role = Admin
  datasource-prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        editable: false
        isDefault: true
        uid: prometheus
  dashboard-kube-state-metrics.yaml: |
    apiVersion: 1
    providers:
      - name: 'kube-state-metrics'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards
