apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: backend-servicemonitor
  name: backend-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    path: metrics
    port: web
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: backend
