apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: javfg/k8s-simple-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-vars
            - secretRef:
                name: db-secret
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web
  selector:
    app: backend
