apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |
    CREATE TABLE mytable (
      message VARCHAR(255)
    );

    INSERT INTO mytable (message)
    VALUES ('This is a sample message');

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: DB_HOST
              value: db-service
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: mydb
          volumeMounts:
            - name: db-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-volume
          configMap:
            name: db-init-script

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
